# Generated by Django 3.1.2 on 2020-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20201214_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='translationText',
            field=models.TextField(null=True),
        ),
    ]
