# Generated by Django 3.1.2 on 2020-11-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201129_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
