# Generated by Django 3.1.2 on 2020-11-29 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201129_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Comment',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
