# Generated by Django 3.1.2 on 2020-12-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
