# Generated by Django 3.1.2 on 2020-12-09 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201208_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static'),
            preserve_default=False,
        ),
    ]
